Add RAII class to lock a surface
mika314/sdlpp pull request #8
Opened 2020-12-03 19:35 UTC by DarthGandalf

2020-12-04 18:12 UTC, mika314 requested changes
Thank you for the PR, just one very small request.

2020-12-04 18:12 UTC, mika314 commented on sdlpp.hpp
> +        Surface& m_s;
I do not like `m_` prefixes. UwU, can you remove it, plz? 
```suggestion
        Surface& s;
```

2020-12-05 02:00 UTC, DarthGandalf commented
Done.

2020-12-05 02:00 UTC, DarthGandalf commented
Perhaps same should be added for Texture and Audio

2020-12-05 08:15 UTC, merged